---
label: Site configuration
hide_body: true
fields:
- type: text
  name: title
  label: Title
  description: Site title
  config:
    required: true
- type: text
  name: baseurl
  label: Base URL
  description: Serve the website from the given base URL
  hidden: true
- type: text
  name: permalink
  label: Permalink
  description: The output path for your pages, posts, or collections.
  hidden: true
  default: "/posts/:slug:output_ext"
- type: text
  name: domain
  label: Domain
  description: The domain of your site, including the protocol, e.g. https://mysite.com/
- type: file
  name: favicon
  label: Favicon
  description: A square icon that represents your website
- type: select
  name: layout_type
  label: Layout
  description: The layout of the site
  default: full-width
  config:
    required: true
    source:
      type: custom
    options:
    - full-width
    - boxed
- type: select
  name: style
  label: Style
  description: The style of the site
  default: classic
  config:
    required: true
    source:
      type: custom
    options:
    - minimal
    - classic
    - bold
- type: select
  name: palette
  label: Palette
  description: The palette of the site
  default: blue
  config:
    required: true
    source:
      type: custom
    options:
    - blue
    - green
    - red
    - gray
- type: select
  name: mode
  label: Mode
  description: The color scheme of the site
  default: dark
  config:
    required: true
    source:
      type: custom
    options:
    - light
    - dark
- type: select
  name: base_font
  label: Font
  default: sans-serif
  config:
    required: true
    source:
      type: custom
    options:
    - sans-serif
    - serif
- type: field_group
  name: header
  label: Header configuration
  fields:
  - type: include
    name: include_header
    label: Header configuration
    template: header
- type: field_group
  name: footer
  label: Footer configuration
  fields:
  - type: include
    name: include_footer
    label: Footer configuration
    template: footer
- type: field_group
  name: sass
  label: Sass
  hidden: true
  fields:
  - type: number
    name: indentWidth
    label: Indent Width
    description: Used to determine the number of spaces or tabs to be used for indentation.
    default: 4
  - type: select
    name: style
    label: Output Style
    description: Determines the output format of the final CSS style.
    default: nested
    config:
      source:
        type: custom
      options:
      - nested
      - expanded
      - compact
      - compressed
  - type: number
    name: precision
    label: Precision
    description: Used to determine how many digits after the decimal will be allowed.
    default: 10
- type: list
  name: plugins
  label: Plugins
  hidden: true
- type: list
  name: exclude
  label: Exclude
  description: Exclude directories and/or files from the conversion.
  hidden: true
pages:
- _config.yml
